// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteDto = { id: bigint, resource_id: bigint, title: string, body_md: string, body_html: string, updated_at: bigint, };
