// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadingContentChunkDto = { status: string, source_type: string, word_count: number, total_blocks: number, offset: number, next_offset: number, has_more: boolean, html: string, };
