// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteDto } from "./NoteDto";
import type { ResourceDto } from "./ResourceDto";

export type ResourceDetailDto = { resource: ResourceDto, notes: Array<NoteDto>, };
