// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResourceInputDto = { kind: string, title: string, author: string | null, url: string | null, file_path: string | null, status: string | null, tags: Array<string>, };
