// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchHitDto = { source_kind: string, source_id: bigint, resource_id: bigint, note_id: bigint | null, title: string, snippet: string, };
