// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchHitDto } from "./SearchHitDto";

export type SearchResponseDto = { query: string, hits: Array<SearchHitDto>, };
